### ISSUE TITLE
Player Permissions

### ISSUE THREAD

**Issue by bristol454** [giggioz/giggioz-better-labels#1]
Anytime as a GM I roll dice my players get the error message" User XXX lack permission to update Chat Message"

![Chat_bug](https://github.com/user-attachments/assets/2a1e54f3-b428-4c4a-b2f7-3c427f76745c)

Disabling this mod prevents the error.

**Comment by giggioz** [comment]
Just released a fix with 1.0.31
https://github.com/giggioz/giggioz-better-labels/releases/tag/v1.0.31
